# Generated by Django 6.0.6 on 2026-06-08 08:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_initial'),
        ('tenants', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_account', to='leads.lead')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_accounts', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'email'], name='users_custo_tenant__36c9a6_idx'), models.Index(fields=['tenant', 'is_active'], name='users_custo_tenant__bf75fc_idx')],
            },
        ),
    ]
