# Generated by Django 6.0.6 on 2026-06-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('activity_type', models.CharField(choices=[('note', 'Note'), ('call_log', 'Call Log'), ('email_log', 'Email Log'), ('sms_log', 'SMS Log'), ('meeting_log', 'Meeting Log'), ('stage_change', 'Stage Change'), ('system', 'System')], default='note', max_length=20)),
                ('body', models.TextField()),
                ('is_private', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('call', 'Call'), ('portal', 'Portal')], max_length=20)),
                ('purpose', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('granted', 'Granted'), ('revoked', 'Revoked'), ('pending', 'Pending')], max_length=20)),
                ('source', models.CharField(max_length=200)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HouseholdMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('relationship', models.CharField(choices=[('primary', 'Primary'), ('spouse', 'Spouse'), ('dependent', 'Dependent'), ('other', 'Other')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='KanbanCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stage', models.CharField(choices=[('new_leads', 'New Leads'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('in_discussion', 'In Discussion'), ('proposal_sent', 'Proposal Sent'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='new_leads', max_length=30)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['stage', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('source', models.CharField(choices=[('web_form', 'Web Form'), ('manual', 'Manual'), ('api_import', 'API Import'), ('email_trigger', 'Email Trigger')], default='manual', max_length=30)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('prospect', 'Prospect'), ('client', 'Client'), ('former_client', 'Former Client'), ('lost', 'Lost'), ('deceased', 'Deceased')], default='lead', max_length=20)),
                ('pipeline_stage', models.CharField(choices=[('new_leads', 'New Leads'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('in_discussion', 'In Discussion'), ('proposal_sent', 'Proposal Sent'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='new_leads', max_length=30)),
                ('preferred_timezone', models.CharField(blank=True, default='', help_text='Lead preferred IANA timezone (e.g. America/Chicago). Falls back to tenant TZ.', max_length=100)),
                ('opted_out', models.BooleanField(default=False)),
                ('is_suppressed', models.BooleanField(default=False)),
                ('portal_enabled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
