# Generated by Django 6.0.6 on 2026-06-07 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('tenants', '0002_initial'),
        ('territories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitynote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitynote',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='household',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='householdmembership',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='leads.household'),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_advisors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['team_lead', 'advisor']}, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='leads.household'),
        ),
        migrations.AddField(
            model_name='lead',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='lead',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='territories.territory'),
        ),
        migrations.AddField(
            model_name='kanbancard',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_card', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='householdmembership',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_memberships', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='activitynote',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_notes', to='leads.lead'),
        ),
        migrations.AddConstraint(
            model_name='household',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_household_name_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant', 'status'], name='leads_lead_tenant__054659_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant', 'pipeline_stage'], name='leads_lead_tenant__a0b8a0_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant', 'email'], name='leads_lead_tenant__0cfaba_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant', 'territory'], name='leads_lead_tenant__92be23_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant', 'created_at'], name='leads_lead_tenant__5e5f75_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(fields=('tenant', 'email'), name='unique_lead_email_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='kanbancard',
            index=models.Index(fields=['stage', 'position'], name='leads_kanba_stage_9cdff6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='householdmembership',
            unique_together={('household', 'lead')},
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['tenant', 'channel', 'state'], name='leads_conse_tenant__132227_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['tenant', 'lead', 'channel'], name='leads_conse_tenant__739abe_idx'),
        ),
        migrations.AddIndex(
            model_name='activitynote',
            index=models.Index(fields=['tenant', 'lead', 'is_private'], name='leads_activ_tenant__33884d_idx'),
        ),
        migrations.AddIndex(
            model_name='activitynote',
            index=models.Index(fields=['tenant', 'created_at'], name='leads_activ_tenant__cd194a_idx'),
        ),
    ]
