# Generated by Django 6.0.6 on 2026-06-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('outcome', models.CharField(blank=True, choices=[('interested', 'Interested'), ('not_interested', 'Not Interested'), ('follow_up', 'Follow Up'), ('closed', 'Closed'), ('no_answer', 'No Answer')], max_length=20)),
                ('recording_ref', models.CharField(blank=True, max_length=500)),
                ('recording_consent_captured', models.BooleanField(default=False)),
                ('ringcentral_call_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('call', 'Call')], max_length=10)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('received', 'Received'), ('bounced', 'Bounced'), ('complained', 'Complained')], default='queued', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_ref', models.CharField(blank=True, max_length=500)),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_reply', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('call', 'Call'), ('all', 'All Channels')], max_length=10)),
                ('purpose', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('granted', 'Granted'), ('revoked', 'Revoked'), ('pending', 'Pending')], max_length=20)),
                ('source', models.CharField(max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_under_legal_hold', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliverabilityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(choices=[('bounce', 'Bounce'), ('complaint', 'Complaint'), ('delivery', 'Delivery'), ('open', 'Open'), ('click', 'Click')], max_length=20)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('raw_payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MailboxConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.CharField(choices=[('gmail', 'Gmail / Google Workspace'), ('outlook', 'Outlook / Microsoft 365')], max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('access_token_enc', models.TextField()),
                ('refresh_token_enc', models.TextField()),
                ('token_expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_cursor', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scheduled_at', models.DateTimeField()),
                ('recipient_timezone', models.CharField(default='UTC', max_length=60)),
                ('zoom_link', models.URLField(blank=True)),
                ('zoom_meeting_id', models.CharField(blank=True, max_length=100)),
                ('calendar_provider', models.CharField(blank=True, max_length=20)),
                ('calendar_event_id', models.CharField(blank=True, max_length=255)),
                ('outcome', models.CharField(blank=True, max_length=100)),
                ('outcome_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reminder_sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='SuppressionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=30)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('all', 'All Channels')], max_length=10)),
                ('reason', models.CharField(choices=[('hard_bounce', 'Hard Bounce'), ('spam_complaint', 'Spam Complaint'), ('sms_optout', 'SMS Opt-Out Keyword'), ('manual', 'Manual Suppression')], max_length=20)),
                ('raw_event', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TriggerDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=253)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
