# Generated by Django 6.0.6 on 2026-06-07 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('communications', '0001_initial'),
        ('leads', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='communication',
            name='campaign_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='campaigns.campaignenrollment'),
        ),
        migrations.AddField(
            model_name='communication',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='communication',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_communications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communication',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='communication',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='call_log', to='communications.communication'),
        ),
        migrations.AddField(
            model_name='consentpreference',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_preferences', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='consentpreference',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='deliverabilityevent',
            name='communication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverability_events', to='communications.communication'),
        ),
        migrations.AddField(
            model_name='deliverabilityevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='mailboxconnection',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailboxconnection',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='suppressionrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='triggerdomain',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['tenant', 'created_at'], name='communicati_tenant__d1124c_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['tenant', 'channel', 'direction'], name='communicati_tenant__bb30d3_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['external_id'], name='communicati_externa_fb2f4e_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['tenant', 'is_reply'], name='communicati_tenant__9f215a_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['tenant', 'is_reply', 'created_at'], name='communicati_tenant__afc591_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['tenant', 'outcome'], name='communicati_tenant__59c2ab_idx'),
        ),
        migrations.AddIndex(
            model_name='consentpreference',
            index=models.Index(fields=['tenant', 'channel', 'state'], name='communicati_tenant__4b4657_idx'),
        ),
        migrations.AddIndex(
            model_name='consentpreference',
            index=models.Index(fields=['tenant', 'lead', 'channel'], name='communicati_tenant__35c4b9_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverabilityevent',
            index=models.Index(fields=['tenant', 'event_type', 'processed'], name='communicati_tenant__471b26_idx'),
        ),
        migrations.AddIndex(
            model_name='mailboxconnection',
            index=models.Index(fields=['tenant', 'status'], name='communicati_tenant__27b75e_idx'),
        ),
        migrations.AddIndex(
            model_name='mailboxconnection',
            index=models.Index(fields=['token_expires_at'], name='communicati_token_e_616c8f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mailboxconnection',
            unique_together={('advisor', 'provider', 'email_address')},
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['tenant', 'advisor', 'scheduled_at'], name='communicati_tenant__de4b1d_idx'),
        ),
        migrations.AddIndex(
            model_name='suppressionrecord',
            index=models.Index(fields=['tenant', 'email', 'channel'], name='communicati_tenant__24a02d_idx'),
        ),
        migrations.AddIndex(
            model_name='suppressionrecord',
            index=models.Index(fields=['tenant', 'phone', 'channel'], name='communicati_tenant__507df2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='triggerdomain',
            unique_together={('tenant', 'domain')},
        ),
    ]
