# Generated by Django 6.0.6 on 2026-06-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
