# Generated by Django 6.0.6 on 2026-06-07 16:29

import apps.timezones.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorTimeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('timezone', models.CharField(help_text='IANA timezone override for this advisor.', max_length=100, validators=[apps.timezones.models.validate_timezone])),
                ('advisor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timezone_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantTimeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('timezone', models.CharField(default='America/New_York', help_text='IANA timezone identifier for the firm office.', max_length=100, validators=[apps.timezones.models.validate_timezone])),
                ('office_start', models.TimeField(default='09:00', help_text='Office opens (in tenant timezone).')),
                ('office_end', models.TimeField(default='17:00', help_text='Office closes (in tenant timezone).')),
                ('working_days', models.JSONField(default=list, help_text='List of weekday integers (0=Mon … 6=Sun) when office is open.')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='one_timezone_config_per_tenant')],
            },
        ),
    ]
