# Generated by Django 6.0.6 on 2026-06-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignExecutionTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('step_order', models.PositiveIntegerField()),
                ('step_type', models.CharField(max_length=10)),
                ('subject_snapshot', models.CharField(blank=True, max_length=500)),
                ('body_snapshot', models.TextField()),
                ('scheduled_at', models.DateTimeField(db_index=True, help_text='UTC datetime, pre-shifted to office hours.')),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('executed', 'Executed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped')], default='pending', max_length=12)),
                ('failure_reason', models.TextField(blank=True)),
                ('was_office_hour_shifted', models.BooleanField(default=False)),
                ('original_scheduled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['enrollment', 'step_order'],
            },
        ),
    ]
