# Generated by Django 6.0.6 on 2026-06-07 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign_timeline', '0001_initial'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignexecutiontimeline',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaignexecutiontimeline',
            name='campaign_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='campaigns.campaignstep'),
        ),
        migrations.AddField(
            model_name='campaignexecutiontimeline',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='campaigns.campaignenrollment'),
        ),
    ]
