# Generated by Django 6.0.6 on 2026-06-07 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign_timeline', '0003_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignexecutiontimeline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='campaignexecutiontimeline',
            index=models.Index(fields=['tenant', 'status', 'scheduled_at'], name='campaign_ti_tenant__0de3be_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignexecutiontimeline',
            index=models.Index(fields=['enrollment', 'step_order'], name='campaign_ti_enrollm_6d176a_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignexecutiontimeline',
            index=models.Index(fields=['lead', 'status'], name='campaign_ti_lead_id_b62e41_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignexecutiontimeline',
            index=models.Index(fields=['campaign', 'status', 'scheduled_at'], name='campaign_ti_campaig_b255f9_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignexecutiontimeline',
            index=models.Index(fields=['tenant', 'scheduled_at'], name='campaign_ti_tenant__7a7faf_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignexecutiontimeline',
            constraint=models.UniqueConstraint(fields=('enrollment', 'campaign_step'), name='unique_timeline_entry_per_enrollment_step'),
        ),
    ]
