# Generated by Django 6.0.6 on 2026-06-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('snapshot_date', models.DateField()),
                ('level', models.CharField(choices=[('platform', 'Platform'), ('firm', 'Firm'), ('advisor', 'Advisor'), ('client', 'Client')], max_length=20)),
                ('entity_id', models.CharField(blank=True, max_length=50)),
                ('metrics', models.JSONField()),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
    ]
