# Generated by Django 6.0.6 on 2026-06-07 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticssnapshot',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['tenant', 'level', 'snapshot_date'], name='analytics_a_tenant__ba1cf5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='analyticssnapshot',
            unique_together={('tenant', 'snapshot_date', 'level', 'entity_id')},
        ),
    ]
