# Generated by Django 6.0.6 on 2026-06-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('doc_type', models.CharField(choices=[('identity', 'Identity'), ('financial', 'Financial'), ('tax', 'Tax'), ('call_recording', 'Call Recording'), ('other', 'Other')], max_length=20)),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('storage_ref', models.CharField(max_length=500)),
                ('version', models.PositiveIntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_under_legal_hold', models.BooleanField(default=False)),
                ('consent_captured', models.BooleanField(default=False)),
                ('retain_until', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
