# Generated by Django 6.0.6 on 2026-06-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entity_type', models.CharField(choices=[('communication', 'Communication'), ('financial', 'Financial Record'), ('document', 'Document'), ('audit', 'Audit Event')], max_length=50)),
                ('retention_years', models.PositiveSmallIntegerField(default=7)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['entity_type'],
            },
        ),
        migrations.CreateModel(
            name='RetentionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=36)),
                ('retained_until', models.DateField()),
                ('is_under_legal_hold', models.BooleanField(default=False)),
                ('hold_placed_at', models.DateTimeField(blank=True, null=True)),
                ('hold_reason', models.TextField(blank=True)),
                ('cleared_for_deletion_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupervisionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupervisionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('all', 'All')], default='all', max_length=10)),
                ('review_mode', models.CharField(choices=[('pre_send', 'Pre-Send Review'), ('post_send', 'Post-Send Review')], default='post_send', max_length=20)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
