# Generated by Django 6.0.6 on 2026-06-07 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0002_initial'),
        ('compliance', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='retentionpolicy',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='retentionrecord',
            name='deletion_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_deletions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retentionrecord',
            name='hold_placed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placed_holds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retentionrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='supervisionreview',
            name='communication',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervision_review', to='communications.communication'),
        ),
        migrations.AddField(
            model_name='supervisionreview',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supervisionreview',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervision_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supervisionreview',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='supervisionrule',
            name='applies_to_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervision_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supervisionrule',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supervisionrule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='supervisionreview',
            name='rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='compliance.supervisionrule'),
        ),
        migrations.AlterUniqueTogether(
            name='retentionpolicy',
            unique_together={('tenant', 'entity_type')},
        ),
        migrations.AddIndex(
            model_name='retentionrecord',
            index=models.Index(fields=['tenant', 'entity_type', 'retained_until'], name='compliance__tenant__11a136_idx'),
        ),
        migrations.AddIndex(
            model_name='retentionrecord',
            index=models.Index(fields=['tenant', 'is_under_legal_hold'], name='compliance__tenant__493774_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='retentionrecord',
            unique_together={('tenant', 'entity_type', 'entity_id')},
        ),
        migrations.AddIndex(
            model_name='supervisionrule',
            index=models.Index(fields=['tenant', 'is_active'], name='compliance__tenant__b16691_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisionreview',
            index=models.Index(fields=['tenant', 'status'], name='compliance__tenant__b72745_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisionreview',
            index=models.Index(fields=['supervisor', 'status'], name='compliance__supervi_d40ded_idx'),
        ),
    ]
