# Generated by Django 6.0.6 on 2026-06-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('stopped', 'Stopped'), ('completed', 'Completed')], default='active', max_length=20)),
                ('current_step', models.PositiveIntegerField(default=0)),
                ('stopped_reason', models.CharField(blank=True, choices=[('response', 'Response'), ('opt_out', 'Opt Out'), ('manual', 'Manual'), ('completed', 'Completed'), ('', 'N/A')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('step_number', models.PositiveIntegerField()),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('content_template', models.TextField()),
                ('delay_days', models.PositiveIntegerField(default=0)),
                ('delay_value', models.PositiveIntegerField(default=0)),
                ('delay_unit', models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], default='days', max_length=10)),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
