# Generated by Django 6.0.6 on 2026-06-07 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('leads', '0001_initial'),
        ('tenants', '0002_initial'),
        ('territories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='territories',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='territories.territory'),
        ),
        migrations.AddField(
            model_name='campaignenrollment',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaignenrollment',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_enrollments', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='campaignenrollment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='campaignstep',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='campaigns.campaign'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_campaign_name_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='campaignenrollment',
            index=models.Index(fields=['tenant', 'status'], name='campaigns_c_tenant__f4135e_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignenrollment',
            constraint=models.CheckConstraint(condition=models.Q(('lead__isnull', False)), name='enrollment_requires_lead'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignstep',
            unique_together={('campaign', 'step_number')},
        ),
    ]
