# Generated by Django 6.0.6 on 2026-06-07 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdvisorTerritory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('advisor', models.ForeignKey(limit_choices_to={'role__in': ['team_lead', 'advisor']}, on_delete=django.db.models.deletion.CASCADE, related_name='advisor_territories', to=settings.AUTH_USER_MODEL)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='territory_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_territories', to='territories.territory')),
            ],
            options={
                'ordering': ['territory__name', 'advisor__last_name'],
            },
        ),
        migrations.AddIndex(
            model_name='territory',
            index=models.Index(fields=['tenant', 'is_active'], name='territories_tenant__0b1556_idx'),
        ),
        migrations.AddIndex(
            model_name='territory',
            index=models.Index(fields=['tenant', 'name'], name='territories_tenant__73a9e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='territory',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_territory_name_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='advisorterritory',
            index=models.Index(fields=['territory', 'advisor'], name='territories_territo_c681a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='advisorterritory',
            unique_together={('advisor', 'territory')},
        ),
    ]
