# Generated by Django 6.0.6 on 2026-06-07 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['status'], name='tenants_ten_status_e7eaee_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['subdomain'], name='tenants_ten_subdoma_6c6a7a_idx'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantbranding',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='tenants.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('user', 'event_type')},
        ),
        migrations.AddIndex(
            model_name='billingrecord',
            index=models.Index(fields=['tenant', 'status'], name='tenants_bil_tenant__536b25_idx'),
        ),
        migrations.AddIndex(
            model_name='billingrecord',
            index=models.Index(fields=['tenant', 'record_type'], name='tenants_bil_tenant__eaafaa_idx'),
        ),
    ]
