# Generated by Django 6.0.6 on 2026-06-07 16:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('calculator_type', models.CharField(choices=[('retirement', 'Retirement Calculator'), ('investment_growth', 'Investment Growth'), ('net_worth', 'Net Worth'), ('loan_amortization', 'Loan / Amortization'), ('college_savings', 'College Savings'), ('insurance_needs', 'Insurance Needs Analysis'), ('risk_assessment', 'Risk Assessment')], max_length=30)),
                ('inputs', models.JSONField()),
                ('outputs', models.JSONField()),
                ('as_of_date', models.DateField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('account_type', models.CharField(choices=[('brokerage', 'Brokerage'), ('ira', 'IRA'), ('401k', '401(k)'), ('bank', 'Bank Account'), ('real_estate', 'Real Estate'), ('retirement', 'Retirement'), ('other', 'Other')], max_length=20)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('as_of_date', models.DateField()),
                ('source', models.CharField(blank=True, max_length=200)),
                ('source_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-as_of_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('goal_type', models.CharField(choices=[('retirement', 'Retirement'), ('home_purchase', 'Home Purchase'), ('education', 'Education'), ('wealth_accumulation', 'Wealth Accumulation'), ('estate_planning', 'Estate Planning'), ('return_target', 'Return Target')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('target_currency', models.CharField(default='USD', max_length=3)),
                ('target_date', models.DateField()),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('progress_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('is_off_track', models.BooleanField(default=False)),
                ('inputs_snapshot', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['target_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('income_currency', models.CharField(default='USD', max_length=3)),
                ('income_as_of', models.DateField(blank=True, null=True)),
                ('annual_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('expenses_currency', models.CharField(default='USD', max_length=3)),
                ('expenses_as_of', models.DateField(blank=True, null=True)),
                ('total_assets', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('assets_currency', models.CharField(default='USD', max_length=3)),
                ('assets_as_of', models.DateField(blank=True, null=True)),
                ('total_liabilities', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('liabilities_currency', models.CharField(default='USD', max_length=3)),
                ('liabilities_as_of', models.DateField(blank=True, null=True)),
                ('risk_tolerance', models.CharField(blank=True, choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('moderately_aggressive', 'Moderately Aggressive'), ('aggressive', 'Aggressive')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GoalMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('target_date', models.DateField()),
                ('is_achieved', models.BooleanField(default=False)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['target_date'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('policy_type', models.CharField(choices=[('life', 'Life'), ('disability', 'Disability'), ('long_term_care', 'Long-Term Care'), ('other', 'Other')], max_length=20)),
                ('provider', models.CharField(blank=True, max_length=200)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('as_of_date', models.DateField()),
                ('premium_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['policy_type'],
            },
        ),
    ]
