# Generated by Django 6.0.6 on 2026-06-07 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financials', '0002_initial'),
        ('leads', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatorresult',
            name='run_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculator_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calculatorresult',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_profile', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='financials.financialprofile'),
        ),
        migrations.AddField(
            model_name='goalmilestone',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='financials.financialgoal'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='financials.financialprofile'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='calculatorresult',
            index=models.Index(fields=['tenant', 'lead', 'calculator_type'], name='financials__tenant__be929c_idx'),
        ),
        migrations.AddIndex(
            model_name='financialgoal',
            index=models.Index(fields=['tenant', 'lead', 'is_off_track'], name='financials__tenant__8cc7de_idx'),
        ),
        migrations.AddIndex(
            model_name='financialprofile',
            index=models.Index(fields=['tenant', 'lead'], name='financials__tenant__e87742_idx'),
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['profile', 'account_type'], name='financials__profile_3fd954_idx'),
        ),
    ]
